# Complete grape varieties data for WineStudy
# Organized by country and type (red/white)

COMPLETE_GRAPES = [
    # ===== FRANCE - RED GRAPES =====
    {"grape_id": "cabernet_sauvignon", "name": "Cabernet Sauvignon", "grape_type": "red", "origin_country": "france",
     "description_pt": "A rainha das uvas tintas, produz vinhos encorpados e estruturados com aromas de cassis, cedro e pimentão verde. Base dos grandes Bordeaux.",
     "description_en": "The queen of red grapes, produces full-bodied, structured wines with aromas of blackcurrant, cedar and green pepper. Base of great Bordeaux.",
     "aromatic_notes": ["Cassis", "Black currant", "Cedar", "Tobacco", "Green pepper", "Mint"],
     "flavor_notes": ["Dark chocolate", "Plum", "Herbs", "Graphite"],
     "structure": {"acidity": "Média-alta", "tannin": "Alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "10-30+ anos", "best_regions": ["Bordeaux", "Napa Valley", "Maipo Valley", "Margaret River", "Coonawarra"], "climate_preference": "Quente a moderado"},
    
    {"grape_id": "merlot", "name": "Merlot", "grape_type": "red", "origin_country": "france",
     "description_pt": "Produz vinhos macios e frutados, frequentemente utilizada em cortes com Cabernet Sauvignon. Estrela de Pomerol e Saint-Émilion.",
     "description_en": "Produces soft, fruity wines, often used in blends with Cabernet Sauvignon. Star of Pomerol and Saint-Émilion.",
     "aromatic_notes": ["Plum", "Cherry", "Chocolate", "Herbs", "Violet"],
     "flavor_notes": ["Red fruits", "Vanilla", "Spice", "Mocha"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-20 anos", "best_regions": ["Bordeaux", "Napa Valley", "Chile", "Friuli"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "pinot_noir", "name": "Pinot Noir", "grape_type": "red", "origin_country": "france",
     "description_pt": "A mais elegante das tintas, difícil de cultivar mas produz vinhos de complexidade incomparável. Estrela da Borgonha.",
     "description_en": "The most elegant of reds, difficult to grow but produces wines of incomparable complexity. Star of Burgundy.",
     "aromatic_notes": ["Raspberry", "Cherry", "Rose", "Earth", "Red berries", "Mushroom", "Forest floor"],
     "flavor_notes": ["Strawberry", "Spice", "Leather", "Tea", "Dried herbs"],
     "structure": {"acidity": "Alta", "tannin": "Baixo a médio", "body": "Leve a médio", "alcohol": "12-14%"},
     "aging_potential": "5-20+ anos", "best_regions": ["Burgundy", "Champagne", "Oregon", "Central Otago", "Sonoma"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "syrah", "name": "Syrah / Shiraz", "grape_type": "red", "origin_country": "france",
     "description_pt": "Produz vinhos potentes e especiados no Rhône e na Austrália. Conhecida como Shiraz no Novo Mundo.",
     "description_en": "Produces powerful, spicy wines in the Rhône and Australia. Known as Shiraz in the New World.",
     "aromatic_notes": ["Blackberry", "Black pepper", "Smoke", "Bacon", "Violet", "Olive"],
     "flavor_notes": ["Dark fruits", "Leather", "Licorice", "Chocolate", "Coffee"],
     "structure": {"acidity": "Média", "tannin": "Médio-alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-25+ anos", "best_regions": ["Rhône", "Barossa Valley", "Stellenbosch", "Washington State"], "climate_preference": "Quente"},
    
    {"grape_id": "grenache", "name": "Grenache / Garnacha", "grape_type": "red", "origin_country": "france",
     "description_pt": "Uva generosa em álcool e frutas maduras, base dos vinhos do Sul do Rhône e da Espanha. Principal componente do Châteauneuf-du-Pape.",
     "description_en": "Generous grape with high alcohol and ripe fruits, base of Southern Rhône and Spanish wines. Main component of Châteauneuf-du-Pape.",
     "aromatic_notes": ["Raspberry", "Strawberry", "Orange peel", "Dried herbs", "White pepper"],
     "flavor_notes": ["Red fruits", "Kirsch", "Spice", "Licorice"],
     "structure": {"acidity": "Baixa a média", "tannin": "Baixo a médio", "body": "Médio a encorpado", "alcohol": "14-16%"},
     "aging_potential": "3-15 anos", "best_regions": ["Rhône", "Priorat", "Rioja", "Sardinia", "Australia"], "climate_preference": "Quente e seco"},
    
    {"grape_id": "cabernet_franc", "name": "Cabernet Franc", "grape_type": "red", "origin_country": "france",
     "description_pt": "Pai do Cabernet Sauvignon, produz vinhos mais leves e herbáceos. Excelente em Chinon e Saint-Émilion.",
     "description_en": "Parent of Cabernet Sauvignon, produces lighter, more herbaceous wines. Excellent in Chinon and Saint-Émilion.",
     "aromatic_notes": ["Raspberry", "Violet", "Green pepper", "Graphite", "Herbs"],
     "flavor_notes": ["Red fruits", "Tobacco", "Earth", "Mint"],
     "structure": {"acidity": "Média-alta", "tannin": "Médio", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Loire Valley", "Bordeaux", "Finger Lakes", "Argentina"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "mourvedre", "name": "Mourvèdre", "grape_type": "red", "origin_country": "france",
     "description_pt": "Uva potente e tânica, componente importante dos vinhos do Rhône e de Bandol. Conhecida como Monastrell na Espanha.",
     "description_en": "Powerful and tannic grape, important component of Rhône and Bandol wines. Known as Monastrell in Spain.",
     "aromatic_notes": ["Blackberry", "Game", "Leather", "Herbs", "Black pepper"],
     "flavor_notes": ["Dark fruits", "Earth", "Meat", "Tar"],
     "structure": {"acidity": "Média", "tannin": "Alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "10-20 anos", "best_regions": ["Bandol", "Rhône", "Jumilla", "Australia"], "climate_preference": "Quente"},
    
    {"grape_id": "malbec", "name": "Malbec", "grape_type": "red", "origin_country": "france",
     "description_pt": "Originária de Cahors na França, encontrou sua expressão máxima na Argentina. Vinhos densos e frutados.",
     "description_en": "Originally from Cahors in France, found its greatest expression in Argentina. Dense, fruity wines.",
     "aromatic_notes": ["Plum", "Blackberry", "Violet", "Cocoa", "Leather"],
     "flavor_notes": ["Dark fruits", "Chocolate", "Coffee", "Spice"],
     "structure": {"acidity": "Média", "tannin": "Médio-alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-15 anos", "best_regions": ["Mendoza", "Cahors", "Salta", "Chile"], "climate_preference": "Quente e seco"},
    
    {"grape_id": "cinsault", "name": "Cinsault", "grape_type": "red", "origin_country": "france",
     "description_pt": "Uva aromática e de cor clara, utilizada em rosés provençais e vinhos do Languedoc. Pai da Pinotage.",
     "description_en": "Aromatic grape with light color, used in Provençal rosés and Languedoc wines. Parent of Pinotage.",
     "aromatic_notes": ["Strawberry", "Cherry", "Floral", "Herbs"],
     "flavor_notes": ["Red fruits", "Spice", "Soft tannins"],
     "structure": {"acidity": "Média", "tannin": "Baixo", "body": "Leve a médio", "alcohol": "12-14%"},
     "aging_potential": "2-5 anos", "best_regions": ["Provence", "Languedoc", "South Africa", "Lebanon"], "climate_preference": "Quente"},
    
    {"grape_id": "carignan", "name": "Carignan", "grape_type": "red", "origin_country": "france",
     "description_pt": "Uva produtiva e rústica, produz vinhos encorpados quando de vinhas velhas. Muito plantada no Languedoc.",
     "description_en": "Productive and rustic grape, produces full-bodied wines from old vines. Widely planted in Languedoc.",
     "aromatic_notes": ["Dark fruits", "Herbs", "Leather", "Spice"],
     "flavor_notes": ["Cherry", "Plum", "Garrigue", "Earth"],
     "structure": {"acidity": "Alta", "tannin": "Alto", "body": "Encorpado", "alcohol": "12-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Languedoc", "Priorat", "Sardinia"], "climate_preference": "Quente e seco"},
    
    {"grape_id": "gamay", "name": "Gamay", "grape_type": "red", "origin_country": "france",
     "description_pt": "A uva do Beaujolais, produz vinhos frescos, frutados e de baixo tanino. Famosa pelo Beaujolais Nouveau.",
     "description_en": "The grape of Beaujolais, produces fresh, fruity, low-tannin wines. Famous for Beaujolais Nouveau.",
     "aromatic_notes": ["Cherry", "Raspberry", "Banana", "Violet", "Peony"],
     "flavor_notes": ["Red fruits", "Cranberry", "Pepper"],
     "structure": {"acidity": "Alta", "tannin": "Baixo", "body": "Leve", "alcohol": "11-13%"},
     "aging_potential": "1-5 anos", "best_regions": ["Beaujolais", "Loire Valley", "Switzerland"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "petit_verdot", "name": "Petit Verdot", "grape_type": "red", "origin_country": "france",
     "description_pt": "Uva de maturação tardia usada em pequenas quantidades nos blends de Bordeaux para adicionar cor e taninos.",
     "description_en": "Late-ripening grape used in small amounts in Bordeaux blends to add color and tannins.",
     "aromatic_notes": ["Violet", "Blackberry", "Smoke", "Pencil lead", "Sage"],
     "flavor_notes": ["Dark fruits", "Leather", "Spice", "Ink"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Encorpado", "alcohol": "13-14%"},
     "aging_potential": "10-25 anos", "best_regions": ["Bordeaux", "Australia", "California", "Spain"], "climate_preference": "Quente"},
    
    # ===== FRANCE - WHITE GRAPES =====
    {"grape_id": "chardonnay", "name": "Chardonnay", "grape_type": "white", "origin_country": "france",
     "description_pt": "A uva branca mais versátil, do Chablis mineral ao estilo amanteigado californiano. Componente do Champagne.",
     "description_en": "The most versatile white grape, from mineral Chablis to buttery California style. Component of Champagne.",
     "aromatic_notes": ["Apple", "Citrus", "Butter", "Oak", "Vanilla", "Tropical fruits"],
     "flavor_notes": ["Pear", "Hazelnut", "Toast", "Cream"],
     "structure": {"acidity": "Média a alta", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "2-15+ anos", "best_regions": ["Burgundy", "Champagne", "California", "Australia"], "climate_preference": "Frio a quente"},
    
    {"grape_id": "sauvignon_blanc", "name": "Sauvignon Blanc", "grape_type": "white", "origin_country": "france",
     "description_pt": "Aromática e refrescante, com notas herbáceas e cítricas marcantes. Famosa em Sancerre e Marlborough.",
     "description_en": "Aromatic and refreshing, with striking herbaceous and citrus notes. Famous in Sancerre and Marlborough.",
     "aromatic_notes": ["Grapefruit", "Grass", "Gooseberry", "Passion fruit", "Elderflower"],
     "flavor_notes": ["Citrus", "Green apple", "Mineral", "Asparagus"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-13%"},
     "aging_potential": "1-5 anos", "best_regions": ["Loire Valley", "Marlborough", "Bordeaux", "Chile"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "semillon", "name": "Sémillon", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva de pele fina, componente essencial de Sauternes e dos brancos de Bordeaux. Excelente em Hunter Valley.",
     "description_en": "Thin-skinned grape, essential component of Sauternes and Bordeaux whites. Excellent in Hunter Valley.",
     "aromatic_notes": ["Honey", "Apricot", "Lanolin", "Fig", "Waxy"],
     "flavor_notes": ["Citrus", "Stone fruit", "Almond", "Toast"],
     "structure": {"acidity": "Baixa a média", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "5-20+ anos", "best_regions": ["Bordeaux", "Hunter Valley", "Chile"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "viognier", "name": "Viognier", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva aromática e opulenta, produz os célebres Condrieu. Notas florais e de damasco intensas.",
     "description_en": "Aromatic and opulent grape, produces the celebrated Condrieu. Intense floral and apricot notes.",
     "aromatic_notes": ["Apricot", "Peach", "Orange blossom", "Honeysuckle", "Musk"],
     "flavor_notes": ["Stone fruit", "Ginger", "Spice", "Cream"],
     "structure": {"acidity": "Baixa a média", "tannin": "N/A", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "1-5 anos", "best_regions": ["Rhône", "California", "Australia", "Chile"], "climate_preference": "Quente"},
    
    {"grape_id": "chenin_blanc", "name": "Chenin Blanc", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva versátil do Loire, de espumantes secos a vinhos doces nobres. Alta acidez e longevidade.",
     "description_en": "Versatile Loire grape, from dry sparkling to noble sweet wines. High acidity and longevity.",
     "aromatic_notes": ["Apple", "Quince", "Honey", "Chamomile", "Wet wool"],
     "flavor_notes": ["Pear", "Ginger", "Waxy", "Almond"],
     "structure": {"acidity": "Muito alta", "tannin": "N/A", "body": "Leve a encorpado", "alcohol": "11-14%"},
     "aging_potential": "5-30+ anos", "best_regions": ["Loire Valley", "South Africa", "California"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "gewurztraminer", "name": "Gewürztraminer", "grape_type": "white", "origin_country": "france",
     "description_pt": "A mais aromática das brancas, com perfume intenso de lichia e rosas. Especialidade da Alsácia.",
     "description_en": "The most aromatic white grape, with intense lychee and rose perfume. Alsace specialty.",
     "aromatic_notes": ["Lychee", "Rose", "Turkish delight", "Ginger", "Spice"],
     "flavor_notes": ["Tropical fruits", "Orange peel", "Honey", "Musk"],
     "structure": {"acidity": "Baixa a média", "tannin": "N/A", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "3-15 anos", "best_regions": ["Alsace", "Germany", "Northern Italy", "New Zealand"], "climate_preference": "Frio"},
    
    {"grape_id": "pinot_gris", "name": "Pinot Gris / Pinot Grigio", "grape_type": "white", "origin_country": "france",
     "description_pt": "Mutação do Pinot Noir, produz vinhos de corpo médio. Rica na Alsácia, leve na Itália.",
     "description_en": "Mutation of Pinot Noir, produces medium-bodied wines. Rich in Alsace, light in Italy.",
     "aromatic_notes": ["Pear", "Apple", "Honey", "Spice", "Smoke"],
     "flavor_notes": ["Stone fruit", "Almond", "Ginger"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "2-10 anos", "best_regions": ["Alsace", "Northern Italy", "Oregon", "New Zealand"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "muscadet", "name": "Muscadet (Melon de Bourgogne)", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva neutra que produz vinhos leves e minerais, perfeitos com frutos do mar. Originária da Borgonha, adotada pelo Loire.",
     "description_en": "Neutral grape producing light, mineral wines, perfect with seafood. Originally from Burgundy, adopted by Loire.",
     "aromatic_notes": ["Citrus", "Apple", "Sea salt", "Mineral"],
     "flavor_notes": ["Lemon", "Saline", "Yeast", "Green apple"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve", "alcohol": "11-12%"},
     "aging_potential": "1-5 anos", "best_regions": ["Loire Valley (Muscadet)"], "climate_preference": "Frio"},
    
    {"grape_id": "marsanne", "name": "Marsanne", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva do norte do Rhône, produz vinhos encorpados e oleosos com notas de amêndoa e pêssego.",
     "description_en": "Northern Rhône grape, produces full-bodied, oily wines with almond and peach notes.",
     "aromatic_notes": ["Almond", "Peach", "Marzipan", "White flowers"],
     "flavor_notes": ["Stone fruit", "Nuts", "Spice", "Honey"],
     "structure": {"acidity": "Baixa a média", "tannin": "N/A", "body": "Encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Rhône", "Australia", "California"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "roussanne", "name": "Roussanne", "grape_type": "white", "origin_country": "france",
     "description_pt": "Parceira da Marsanne no Rhône, mais elegante e aromática. Notas de chá e ervas.",
     "description_en": "Marsanne's partner in Rhône, more elegant and aromatic. Tea and herbal notes.",
     "aromatic_notes": ["Tea", "Pear", "Herbs", "Honey", "Chamomile"],
     "flavor_notes": ["Stone fruit", "Floral", "Mineral"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Rhône", "California", "Australia"], "climate_preference": "Moderado"},
    
    {"grape_id": "picpoul", "name": "Picpoul / Piquepoul", "grape_type": "white", "origin_country": "france",
     "description_pt": "Uva refrescante do Languedoc, ideal para acompanhar ostras. Alta acidez e notas cítricas.",
     "description_en": "Refreshing Languedoc grape, ideal with oysters. High acidity and citrus notes.",
     "aromatic_notes": ["Citrus", "White flowers", "Herbs", "Mineral"],
     "flavor_notes": ["Lemon", "Green apple", "Saline", "Almond"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "12-13%"},
     "aging_potential": "1-3 anos", "best_regions": ["Languedoc (Pinet)"], "climate_preference": "Quente"},
    
    # ===== ITALY - RED GRAPES =====
    {"grape_id": "nebbiolo", "name": "Nebbiolo", "grape_type": "red", "origin_country": "italy",
     "description_pt": "A nobre uva do Piemonte, produz Barolo e Barbaresco. Vinhos de cor clara mas intensamente tânicos.",
     "description_en": "The noble grape of Piedmont, producing Barolo and Barbaresco. Light-colored but intensely tannic wines.",
     "aromatic_notes": ["Rose", "Tar", "Cherry", "Truffle", "Leather", "Dried herbs"],
     "flavor_notes": ["Red cherry", "Licorice", "Tea", "Tobacco"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Médio a encorpado", "alcohol": "13-15%"},
     "aging_potential": "15-40+ anos", "best_regions": ["Piedmont (Barolo, Barbaresco)", "Lombardy (Valtellina)"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "sangiovese", "name": "Sangiovese", "grape_type": "red", "origin_country": "italy",
     "description_pt": "A uva mais plantada da Itália, base do Chianti, Brunello e Vino Nobile. Cereja, terra e taninos firmes.",
     "description_en": "Italy's most planted grape, base of Chianti, Brunello and Vino Nobile. Cherry, earth and firm tannins.",
     "aromatic_notes": ["Cherry", "Tomato leaf", "Leather", "Earth", "Tea", "Violet"],
     "flavor_notes": ["Sour cherry", "Herbs", "Tobacco", "Spice"],
     "structure": {"acidity": "Alta", "tannin": "Médio-alto", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "5-25+ anos", "best_regions": ["Tuscany", "Romagna", "Argentina"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "barbera", "name": "Barbera", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva piemontesa de alta acidez e baixo tanino, produz vinhos frutados e versáteis.",
     "description_en": "Piedmontese grape with high acidity and low tannin, produces fruity, versatile wines.",
     "aromatic_notes": ["Cherry", "Raspberry", "Plum", "Spice", "Herbs"],
     "flavor_notes": ["Red fruits", "Almond", "Licorice"],
     "structure": {"acidity": "Alta", "tannin": "Baixo a médio", "body": "Médio", "alcohol": "13-15%"},
     "aging_potential": "3-10 anos", "best_regions": ["Piedmont (Asti, Alba)", "California"], "climate_preference": "Moderado"},
    
    {"grape_id": "dolcetto", "name": "Dolcetto", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva piemontesa 'doce' (no nome, não no sabor), produz vinhos frutados para consumo jovem.",
     "description_en": "Piedmontese 'sweet' grape (in name, not taste), produces fruity wines for young consumption.",
     "aromatic_notes": ["Blackberry", "Cherry", "Violet", "Licorice", "Almond"],
     "flavor_notes": ["Dark fruits", "Bitter almond", "Herbs"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Piedmont (Dogliani, Alba, Ovada)"], "climate_preference": "Moderado"},
    
    {"grape_id": "corvina", "name": "Corvina", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Principal uva do Valpolicella e Amarone. Aromas de cereja ácida e amêndoa amarga.",
     "description_en": "Main grape of Valpolicella and Amarone. Sour cherry and bitter almond aromas.",
     "aromatic_notes": ["Sour cherry", "Almond", "Herbs", "Dried fruits"],
     "flavor_notes": ["Cherry", "Chocolate", "Coffee", "Raisins"],
     "structure": {"acidity": "Alta", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "12-16%"},
     "aging_potential": "5-20 anos", "best_regions": ["Veneto (Valpolicella)"], "climate_preference": "Moderado"},
    
    {"grape_id": "nero_davola", "name": "Nero d'Avola", "grape_type": "red", "origin_country": "italy",
     "description_pt": "A uva tinta mais importante da Sicília, produz vinhos encorpados e frutados com notas de ameixa.",
     "description_en": "Sicily's most important red grape, produces full-bodied, fruity wines with plum notes.",
     "aromatic_notes": ["Plum", "Cherry", "Chocolate", "Spice", "Dried herbs"],
     "flavor_notes": ["Dark fruits", "Licorice", "Coffee", "Pepper"],
     "structure": {"acidity": "Média", "tannin": "Médio-alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-15 anos", "best_regions": ["Sicily"], "climate_preference": "Quente"},
    
    {"grape_id": "primitivo", "name": "Primitivo", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Geneticamente idêntica à Zinfandel, produz vinhos potentes e frutados na Puglia.",
     "description_en": "Genetically identical to Zinfandel, produces powerful, fruity wines in Puglia.",
     "aromatic_notes": ["Blackberry", "Plum", "Prune", "Spice", "Chocolate"],
     "flavor_notes": ["Jam", "Raisins", "Vanilla", "Pepper"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Encorpado", "alcohol": "14-17%"},
     "aging_potential": "3-10 anos", "best_regions": ["Puglia (Manduria)", "California (as Zinfandel)"], "climate_preference": "Quente"},
    
    {"grape_id": "aglianico", "name": "Aglianico", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva antiga do sul da Itália, produz vinhos poderosos e de grande longevidade. Barolo do Sul.",
     "description_en": "Ancient Southern Italian grape, produces powerful, long-lived wines. Barolo of the South.",
     "aromatic_notes": ["Dark cherry", "Plum", "Smoke", "Leather", "Tar", "Herbs"],
     "flavor_notes": ["Dark fruits", "Chocolate", "Coffee", "Earth"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "10-30+ anos", "best_regions": ["Campania (Taurasi)", "Basilicata (Aglianico del Vulture)"], "climate_preference": "Quente"},
    
    {"grape_id": "montepulciano", "name": "Montepulciano", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva versátil do centro-sul da Itália, produz vinhos frutados e macios para consumo diário.",
     "description_en": "Versatile central-southern Italian grape, produces fruity, soft wines for daily consumption.",
     "aromatic_notes": ["Cherry", "Plum", "Violet", "Pepper", "Herbs"],
     "flavor_notes": ["Red fruits", "Earth", "Spice", "Licorice"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "3-10 anos", "best_regions": ["Abruzzo", "Marche"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "nerello_mascalese", "name": "Nerello Mascalese", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva vulcânica do Etna, produz vinhos elegantes comparados a Pinot Noir e Nebbiolo.",
     "description_en": "Volcanic Etna grape, produces elegant wines compared to Pinot Noir and Nebbiolo.",
     "aromatic_notes": ["Cherry", "Blood orange", "Herbs", "Smoke", "Mineral"],
     "flavor_notes": ["Red fruits", "Tea", "Volcanic ash", "Spice"],
     "structure": {"acidity": "Alta", "tannin": "Médio-alto", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "10-25 anos", "best_regions": ["Sicily (Etna)"], "climate_preference": "Moderado"},
    
    {"grape_id": "sagrantino", "name": "Sagrantino", "grape_type": "red", "origin_country": "italy",
     "description_pt": "Uva tânica da Úmbria, produz os vinhos mais tânicos da Itália em Montefalco.",
     "description_en": "Tannic Umbrian grape, produces Italy's most tannic wines in Montefalco.",
     "aromatic_notes": ["Blackberry", "Plum", "Herbs", "Smoke", "Leather"],
     "flavor_notes": ["Dark fruits", "Earth", "Tar", "Chocolate"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Encorpado", "alcohol": "14-16%"},
     "aging_potential": "10-25 anos", "best_regions": ["Umbria (Montefalco)"], "climate_preference": "Moderado"},
    
    # ===== ITALY - WHITE GRAPES =====
    {"grape_id": "garganega", "name": "Garganega", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Principal uva do Soave, produz vinhos leves e aromáticos com notas de amêndoa.",
     "description_en": "Main grape of Soave, produces light, aromatic wines with almond notes.",
     "aromatic_notes": ["Almond", "White flowers", "Citrus", "Mineral"],
     "flavor_notes": ["Green apple", "Pear", "Honey"],
     "structure": {"acidity": "Média-alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Veneto (Soave)"], "climate_preference": "Moderado"},
    
    {"grape_id": "trebbiano", "name": "Trebbiano / Ugni Blanc", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva branca mais plantada da Itália, produz vinhos neutros. Na França, base do Cognac.",
     "description_en": "Italy's most planted white grape, produces neutral wines. In France, base of Cognac.",
     "aromatic_notes": ["Citrus", "Green apple", "Almond", "Mineral"],
     "flavor_notes": ["Light", "Fresh", "Neutral"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve", "alcohol": "11-12%"},
     "aging_potential": "1-3 anos", "best_regions": ["Central Italy", "Cognac (France)"], "climate_preference": "Moderado"},
    
    {"grape_id": "verdicchio", "name": "Verdicchio", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva das Marche, produz vinhos frescos e minerais com potencial de envelhecimento.",
     "description_en": "Marche grape, produces fresh, mineral wines with aging potential.",
     "aromatic_notes": ["Citrus", "Green apple", "Almond", "Fennel", "Mineral"],
     "flavor_notes": ["Lemon", "Herbs", "Saline", "Bitter almond"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "3-10 anos", "best_regions": ["Marche (Castelli di Jesi, Matelica)"], "climate_preference": "Moderado"},
    
    {"grape_id": "vermentino", "name": "Vermentino", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva mediterrânea aromática, popular na Sardenha e Ligúria. Notas herbáceas e cítricas.",
     "description_en": "Aromatic Mediterranean grape, popular in Sardinia and Liguria. Herbaceous and citrus notes.",
     "aromatic_notes": ["Lime", "Grapefruit", "Herbs", "White flowers", "Almond"],
     "flavor_notes": ["Citrus", "Green apple", "Mineral", "Saline"],
     "structure": {"acidity": "Média-alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "12-13%"},
     "aging_potential": "1-3 anos", "best_regions": ["Sardinia", "Liguria", "Provence"], "climate_preference": "Quente"},
    
    {"grape_id": "fiano", "name": "Fiano", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Antiga uva campana, produz vinhos complexos com notas de mel e nozes.",
     "description_en": "Ancient Campanian grape, produces complex wines with honey and nut notes.",
     "aromatic_notes": ["Honey", "Hazelnut", "White flowers", "Citrus", "Spice"],
     "flavor_notes": ["Pear", "Almond", "Mineral", "Smoke"],
     "structure": {"acidity": "Média-alta", "tannin": "N/A", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "5-15 anos", "best_regions": ["Campania (Avellino)"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "greco", "name": "Greco", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva grega antiga cultivada na Campânia, produz vinhos estruturados e minerais.",
     "description_en": "Ancient Greek grape grown in Campania, produces structured, mineral wines.",
     "aromatic_notes": ["Citrus", "Peach", "Almond", "Herbs", "Mineral"],
     "flavor_notes": ["Stone fruit", "Bitter almond", "Honey"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "3-10 anos", "best_regions": ["Campania (Tufo)"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "arneis", "name": "Arneis", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva piemontesa quase extinta, revivida nos anos 80. Vinhos florais e delicados.",
     "description_en": "Nearly extinct Piedmontese grape, revived in the 1980s. Floral, delicate wines.",
     "aromatic_notes": ["Pear", "Apricot", "White flowers", "Almond", "Honey"],
     "flavor_notes": ["Stone fruit", "Herbs", "Bitter almond"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "1-3 anos", "best_regions": ["Piedmont (Roero)"], "climate_preference": "Moderado"},
    
    {"grape_id": "cortese", "name": "Cortese", "grape_type": "white", "origin_country": "italy",
     "description_pt": "Uva do Gavi, produz vinhos frescos e minerais do Piemonte.",
     "description_en": "Gavi grape, produces fresh, mineral wines from Piedmont.",
     "aromatic_notes": ["Citrus", "Green apple", "White flowers", "Mineral", "Almond"],
     "flavor_notes": ["Lemon", "Herbs", "Saline"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-12%"},
     "aging_potential": "1-5 anos", "best_regions": ["Piedmont (Gavi)"], "climate_preference": "Moderado"},
    
    # ===== SPAIN - RED GRAPES =====
    {"grape_id": "tempranillo", "name": "Tempranillo", "grape_type": "red", "origin_country": "spain",
     "description_pt": "A grande uva tinta espanhola, base de Rioja e Ribera del Duero. Amadurece cedo (temprano).",
     "description_en": "Spain's great red grape, base of Rioja and Ribera del Duero. Ripens early (temprano).",
     "aromatic_notes": ["Cherry", "Plum", "Leather", "Tobacco", "Vanilla", "Dried herbs"],
     "flavor_notes": ["Red fruits", "Earth", "Spice", "Coconut"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-25+ anos", "best_regions": ["Rioja", "Ribera del Duero", "Toro", "Portugal (Aragonez)"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "garnacha", "name": "Garnacha / Grenache", "grape_type": "red", "origin_country": "spain",
     "description_pt": "Originária de Aragão, uma das uvas mais plantadas do mundo. Vinhos generosos e frutados.",
     "description_en": "Originally from Aragon, one of the most planted grapes in the world. Generous, fruity wines.",
     "aromatic_notes": ["Raspberry", "Strawberry", "Orange peel", "White pepper", "Dried herbs", "Garrigue"],
     "flavor_notes": ["Red fruits", "Kirsch", "Spice", "Licorice"],
     "structure": {"acidity": "Baixa a média", "tannin": "Baixo a médio", "body": "Médio a encorpado", "alcohol": "14-16%"},
     "aging_potential": "3-15 anos", "best_regions": ["Priorat", "Navarra", "Rhône", "Sardinia"], "climate_preference": "Quente e seco"},
    
    {"grape_id": "monastrell", "name": "Monastrell / Mourvèdre", "grape_type": "red", "origin_country": "spain",
     "description_pt": "Uva potente do Levante espanhol, produz vinhos densos e carnosos.",
     "description_en": "Powerful grape from the Spanish Levante, produces dense, meaty wines.",
     "aromatic_notes": ["Blackberry", "Plum", "Leather", "Game", "Herbs", "Black pepper"],
     "flavor_notes": ["Dark fruits", "Earth", "Meat", "Tar"],
     "structure": {"acidity": "Média", "tannin": "Alto", "body": "Encorpado", "alcohol": "14-16%"},
     "aging_potential": "5-15 anos", "best_regions": ["Jumilla", "Yecla", "Alicante", "Bandol"], "climate_preference": "Quente"},
    
    {"grape_id": "mencia", "name": "Mencía", "grape_type": "red", "origin_country": "spain",
     "description_pt": "Uva elegante do noroeste espanhol, produz vinhos comparados a Pinot Noir.",
     "description_en": "Elegant grape from northwest Spain, produces wines compared to Pinot Noir.",
     "aromatic_notes": ["Cherry", "Violet", "Herbs", "Mineral", "Floral"],
     "flavor_notes": ["Red fruits", "Slate", "Spice", "Earth"],
     "structure": {"acidity": "Alta", "tannin": "Médio", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Bierzo", "Ribeira Sacra", "Valdeorras"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "bobal", "name": "Bobal", "grape_type": "red", "origin_country": "spain",
     "description_pt": "Segunda uva mais plantada da Espanha, produz vinhos frutados e acessíveis em Utiel-Requena.",
     "description_en": "Spain's second most planted grape, produces fruity, accessible wines in Utiel-Requena.",
     "aromatic_notes": ["Blackberry", "Cherry", "Violet", "Herbs", "Earth"],
     "flavor_notes": ["Dark fruits", "Licorice", "Mineral"],
     "structure": {"acidity": "Alta", "tannin": "Médio-alto", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "3-10 anos", "best_regions": ["Utiel-Requena", "Manchuela"], "climate_preference": "Quente e seco"},
    
    {"grape_id": "graciano", "name": "Graciano", "grape_type": "red", "origin_country": "spain",
     "description_pt": "Uva aromática de Rioja, usada em pequenas quantidades para adicionar cor e frescor.",
     "description_en": "Aromatic Rioja grape, used in small amounts to add color and freshness.",
     "aromatic_notes": ["Blackberry", "Violet", "Herbs", "Spice", "Licorice"],
     "flavor_notes": ["Dark fruits", "Mint", "Earth"],
     "structure": {"acidity": "Alta", "tannin": "Alto", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "10-20 anos", "best_regions": ["Rioja", "Navarra"], "climate_preference": "Moderado"},
    
    # ===== SPAIN - WHITE GRAPES =====
    {"grape_id": "albarino", "name": "Albariño", "grape_type": "white", "origin_country": "spain",
     "description_pt": "A grande uva branca da Galícia, produz vinhos aromáticos e refrescantes em Rías Baixas.",
     "description_en": "Galicia's great white grape, produces aromatic, refreshing wines in Rías Baixas.",
     "aromatic_notes": ["Peach", "Apricot", "Citrus", "White flowers", "Saline"],
     "flavor_notes": ["Stone fruit", "Lemon", "Mineral", "Herbs"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "12-13%"},
     "aging_potential": "1-5 anos", "best_regions": ["Rías Baixas", "Vinho Verde (Portugal)"], "climate_preference": "Frio e úmido"},
    
    {"grape_id": "verdejo", "name": "Verdejo", "grape_type": "white", "origin_country": "spain",
     "description_pt": "Uva aromática de Rueda, com notas herbáceas e de erva-doce. Renascimento nos anos 80.",
     "description_en": "Aromatic Rueda grape, with herbaceous and fennel notes. Renaissance in the 1980s.",
     "aromatic_notes": ["Citrus", "Fennel", "Grass", "White flowers", "Tropical"],
     "flavor_notes": ["Grapefruit", "Herbs", "Bitter almond"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "1-5 anos", "best_regions": ["Rueda"], "climate_preference": "Moderado e seco"},
    
    {"grape_id": "godello", "name": "Godello", "grape_type": "white", "origin_country": "spain",
     "description_pt": "Uva renascentista da Galícia e Bierzo, produz vinhos encorpados e minerais.",
     "description_en": "Renaissance grape from Galicia and Bierzo, produces full-bodied, mineral wines.",
     "aromatic_notes": ["Peach", "Apple", "Herbs", "Mineral", "Smoke"],
     "flavor_notes": ["Stone fruit", "Citrus", "Almond", "Honey"],
     "structure": {"acidity": "Média-alta", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "3-10 anos", "best_regions": ["Valdeorras", "Bierzo", "Monterrei"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "viura", "name": "Viura / Macabeo", "grape_type": "white", "origin_country": "spain",
     "description_pt": "Uva versátil, principal componente do Rioja branco e do Cava.",
     "description_en": "Versatile grape, main component of white Rioja and Cava.",
     "aromatic_notes": ["Apple", "Citrus", "White flowers", "Almond"],
     "flavor_notes": ["Pear", "Herbs", "Mineral"],
     "structure": {"acidity": "Média-alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-13%"},
     "aging_potential": "1-10 anos", "best_regions": ["Rioja", "Catalonia (Cava)", "Languedoc"], "climate_preference": "Moderado"},
    
    {"grape_id": "xarello", "name": "Xarel·lo", "grape_type": "white", "origin_country": "spain",
     "description_pt": "Uva catalana essencial para o Cava, contribui com estrutura e notas terrosas.",
     "description_en": "Catalan grape essential for Cava, contributes structure and earthy notes.",
     "aromatic_notes": ["Apple", "Earth", "Herbs", "Citrus", "Mineral"],
     "flavor_notes": ["Pear", "Almond", "Honey"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio", "alcohol": "11-13%"},
     "aging_potential": "3-10 anos", "best_regions": ["Penedès", "Catalonia"], "climate_preference": "Moderado"},
    
    {"grape_id": "parellada", "name": "Parellada", "grape_type": "white", "origin_country": "spain",
     "description_pt": "Uva delicada do Cava, cultivada em altitude para manter a acidez. Notas florais.",
     "description_en": "Delicate Cava grape, grown at altitude to maintain acidity. Floral notes.",
     "aromatic_notes": ["White flowers", "Apple", "Citrus", "Herbs"],
     "flavor_notes": ["Pear", "Almond", "Light"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve", "alcohol": "10-12%"},
     "aging_potential": "1-3 anos", "best_regions": ["Penedès", "Catalonia"], "climate_preference": "Frio"},
    
    # ===== PORTUGAL - RED GRAPES =====
    {"grape_id": "touriga_nacional", "name": "Touriga Nacional", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "A mais nobre uva portuguesa, base dos melhores vinhos do Porto e Douro. Intensa e aromática.",
     "description_en": "Portugal's noblest grape, base of the best Port and Douro wines. Intense and aromatic.",
     "aromatic_notes": ["Violet", "Blackberry", "Rock rose", "Mint", "Blueberry"],
     "flavor_notes": ["Dark fruits", "Chocolate", "Herbs", "Licorice"],
     "structure": {"acidity": "Média-alta", "tannin": "Alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "10-30+ anos", "best_regions": ["Douro", "Dão", "Alentejo"], "climate_preference": "Quente"},
    
    {"grape_id": "touriga_franca", "name": "Touriga Franca", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "A casta mais plantada do Douro, parceira da Touriga Nacional nos grandes blends.",
     "description_en": "The most planted grape in Douro, partner of Touriga Nacional in great blends.",
     "aromatic_notes": ["Floral", "Cherry", "Strawberry", "Herbs", "Spice"],
     "flavor_notes": ["Red fruits", "Roses", "Pepper"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Douro"], "climate_preference": "Quente"},
    
    {"grape_id": "tinta_roriz", "name": "Tinta Roriz / Aragonez", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "A Tempranillo em Portugal, importante no Douro e Alentejo. Vinhos elegantes e frutados.",
     "description_en": "Tempranillo in Portugal, important in Douro and Alentejo. Elegant, fruity wines.",
     "aromatic_notes": ["Cherry", "Plum", "Tobacco", "Leather", "Herbs"],
     "flavor_notes": ["Red fruits", "Spice", "Earth"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Douro", "Alentejo", "Dão"], "climate_preference": "Quente"},
    
    {"grape_id": "baga", "name": "Baga", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "A casta da Bairrada, taninos firmes e acidez alta. Potencial de envelhecimento excepcional.",
     "description_en": "The Bairrada grape, firm tannins and high acidity. Exceptional aging potential.",
     "aromatic_notes": ["Dark cherry", "Plum", "Herbs", "Earth", "Forest floor"],
     "flavor_notes": ["Red fruits", "Leather", "Tobacco", "Tea"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Médio a encorpado", "alcohol": "12-13%"},
     "aging_potential": "10-30+ anos", "best_regions": ["Bairrada"], "climate_preference": "Moderado"},
    
    {"grape_id": "castelao", "name": "Castelão", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "Uva versátil do sul de Portugal, produz vinhos macios e frutados na Península de Setúbal.",
     "description_en": "Versatile grape from southern Portugal, produces soft, fruity wines in Setúbal Peninsula.",
     "aromatic_notes": ["Strawberry", "Cherry", "Herbs", "Earth", "Spice"],
     "flavor_notes": ["Red fruits", "Pepper", "Tobacco"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "3-10 anos", "best_regions": ["Península de Setúbal", "Tejo"], "climate_preference": "Quente"},
    
    {"grape_id": "tinta_cao", "name": "Tinta Cão", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "Casta rara mas valiosa do Douro, adiciona elegância e acidez aos blends.",
     "description_en": "Rare but valuable Douro grape, adds elegance and acidity to blends.",
     "aromatic_notes": ["Floral", "Cherry", "Herbs", "Mineral"],
     "flavor_notes": ["Red fruits", "Spice", "Earth"],
     "structure": {"acidity": "Alta", "tannin": "Médio-alto", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "10-25 anos", "best_regions": ["Douro"], "climate_preference": "Quente"},
    
    {"grape_id": "trincadeira", "name": "Trincadeira", "grape_type": "red", "origin_country": "portugal",
     "description_pt": "Casta aromática do Alentejo, produz vinhos florais e especiados.",
     "description_en": "Aromatic Alentejo grape, produces floral and spicy wines.",
     "aromatic_notes": ["Blackberry", "Violet", "Pepper", "Herbs", "Licorice"],
     "flavor_notes": ["Dark fruits", "Spice", "Earth"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-12 anos", "best_regions": ["Alentejo", "Tejo"], "climate_preference": "Quente"},
    
    # ===== PORTUGAL - WHITE GRAPES =====
    {"grape_id": "alvarinho", "name": "Alvarinho", "grape_type": "white", "origin_country": "portugal",
     "description_pt": "A mesma Albariño espanhola, produz os melhores vinhos do Vinho Verde. Aromática e complexa.",
     "description_en": "The same as Spanish Albariño, produces the best Vinho Verde wines. Aromatic and complex.",
     "aromatic_notes": ["Peach", "Apricot", "Citrus", "White flowers", "Mineral"],
     "flavor_notes": ["Stone fruit", "Lemon", "Herbs"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Vinho Verde (Monção e Melgaço)"], "climate_preference": "Frio e úmido"},
    
    {"grape_id": "loureiro", "name": "Loureiro", "grape_type": "white", "origin_country": "portugal",
     "description_pt": "Uva aromática do Vinho Verde, com intensas notas de louro (daí o nome) e flores.",
     "description_en": "Aromatic Vinho Verde grape, with intense bay leaf (hence the name) and floral notes.",
     "aromatic_notes": ["Bay leaf", "Orange blossom", "Citrus", "Acacia", "Peach"],
     "flavor_notes": ["Lemon", "Herbs", "Floral"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve", "alcohol": "11-12%"},
     "aging_potential": "1-3 anos", "best_regions": ["Vinho Verde"], "climate_preference": "Frio e úmido"},
    
    {"grape_id": "encruzado", "name": "Encruzado", "grape_type": "white", "origin_country": "portugal",
     "description_pt": "A grande uva branca do Dão, produz vinhos elegantes e com potencial de envelhecimento.",
     "description_en": "The great white grape of Dão, produces elegant wines with aging potential.",
     "aromatic_notes": ["Citrus", "White flowers", "Mineral", "Smoke", "Honey"],
     "flavor_notes": ["Stone fruit", "Herbs", "Toast"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Dão"], "climate_preference": "Moderado"},
    
    {"grape_id": "arinto", "name": "Arinto", "grape_type": "white", "origin_country": "portugal",
     "description_pt": "Uva de alta acidez cultivada em todo Portugal, essencial para manter frescor nos vinhos.",
     "description_en": "High-acidity grape grown throughout Portugal, essential for keeping wines fresh.",
     "aromatic_notes": ["Citrus", "Apple", "Mineral", "Herbs"],
     "flavor_notes": ["Lemon", "Green apple", "Saline"],
     "structure": {"acidity": "Muito alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-13%"},
     "aging_potential": "3-10 anos", "best_regions": ["Bucelas", "Vinho Verde", "Alentejo"], "climate_preference": "Moderado"},
    
    {"grape_id": "fernao_pires", "name": "Fernão Pires / Maria Gomes", "grape_type": "white", "origin_country": "portugal",
     "description_pt": "A uva branca mais plantada em Portugal, versátil e aromática.",
     "description_en": "Portugal's most planted white grape, versatile and aromatic.",
     "aromatic_notes": ["Orange blossom", "Citrus", "Rose", "Tropical"],
     "flavor_notes": ["Peach", "Melon", "Herbs"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio", "alcohol": "11-13%"},
     "aging_potential": "1-3 anos", "best_regions": ["Tejo", "Bairrada", "Lisboa"], "climate_preference": "Moderado a quente"},
    
    # ===== GERMANY - WHITE GRAPES =====
    {"grape_id": "riesling", "name": "Riesling", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Rainha das uvas brancas alemãs, do seco ao doce, sempre com acidez vibrante. Envelhece magnificamente.",
     "description_en": "Queen of German white grapes, from dry to sweet, always with vibrant acidity. Ages magnificently.",
     "aromatic_notes": ["Lime", "Peach", "Petrol", "Honey", "Slate", "Apricot"],
     "flavor_notes": ["Apple", "Mineral", "Ginger", "White flowers"],
     "structure": {"acidity": "Muito alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "8-13%"},
     "aging_potential": "5-30+ anos", "best_regions": ["Mosel", "Rheingau", "Pfalz", "Alsace", "Clare Valley"], "climate_preference": "Frio"},
    
    {"grape_id": "muller_thurgau", "name": "Müller-Thurgau", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Cruzamento de Riesling x Madeleine Royale, produz vinhos leves e aromáticos.",
     "description_en": "Riesling x Madeleine Royale cross, produces light, aromatic wines.",
     "aromatic_notes": ["Muscat", "Peach", "Citrus", "Herbs"],
     "flavor_notes": ["Light", "Floral", "Fresh"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Leve", "alcohol": "9-11%"},
     "aging_potential": "1-2 anos", "best_regions": ["Germany", "Austria", "Northern Italy"], "climate_preference": "Frio"},
    
    {"grape_id": "silvaner", "name": "Silvaner", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Uva tradicional de Franken, produz vinhos secos e terrosos na garrafa Bocksbeutel.",
     "description_en": "Traditional Franken grape, produces dry, earthy wines in the Bocksbeutel bottle.",
     "aromatic_notes": ["Apple", "Earth", "Herbs", "Mineral"],
     "flavor_notes": ["Citrus", "Almond", "Neutral"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio", "alcohol": "11-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Franken", "Alsace"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "grauburgunder", "name": "Grauburgunder / Pinot Gris", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Pinot Gris na Alemanha, produz vinhos mais secos e estruturados que a versão italiana.",
     "description_en": "Pinot Gris in Germany, produces drier, more structured wines than the Italian version.",
     "aromatic_notes": ["Pear", "Apple", "Honey", "Spice", "Smoke"],
     "flavor_notes": ["Stone fruit", "Almond", "Ginger"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio a encorpado", "alcohol": "12-14%"},
     "aging_potential": "2-8 anos", "best_regions": ["Baden", "Pfalz"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "weissburgunder", "name": "Weissburgunder / Pinot Blanc", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Pinot Blanc na Alemanha, vinhos secos e elegantes, boa alternativa ao Chardonnay.",
     "description_en": "Pinot Blanc in Germany, dry and elegant wines, good Chardonnay alternative.",
     "aromatic_notes": ["Apple", "Pear", "Almond", "Cream", "Mineral"],
     "flavor_notes": ["Stone fruit", "Bread", "Nuts"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Baden", "Pfalz", "Alsace"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "scheurebe", "name": "Scheurebe", "grape_type": "white", "origin_country": "germany",
     "description_pt": "Cruzamento alemão aromático, produz vinhos com notas de cassis e groselha.",
     "description_en": "Aromatic German cross, produces wines with blackcurrant and gooseberry notes.",
     "aromatic_notes": ["Blackcurrant", "Grapefruit", "Peach", "Herbs"],
     "flavor_notes": ["Citrus", "Tropical", "Spice"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Médio", "alcohol": "11-13%"},
     "aging_potential": "2-10 anos", "best_regions": ["Pfalz", "Rheinhessen"], "climate_preference": "Frio"},
    
    # ===== GERMANY - RED GRAPES =====
    {"grape_id": "spatburgunder", "name": "Spätburgunder / Pinot Noir", "grape_type": "red", "origin_country": "germany",
     "description_pt": "Pinot Noir na Alemanha, produz vinhos elegantes em Baden e Ahr.",
     "description_en": "Pinot Noir in Germany, produces elegant wines in Baden and Ahr.",
     "aromatic_notes": ["Cherry", "Raspberry", "Rose", "Earth", "Smoke"],
     "flavor_notes": ["Red fruits", "Spice", "Tea"],
     "structure": {"acidity": "Alta", "tannin": "Baixo a médio", "body": "Leve a médio", "alcohol": "12-14%"},
     "aging_potential": "5-15 anos", "best_regions": ["Baden", "Ahr", "Pfalz"], "climate_preference": "Frio a moderado"},
    
    {"grape_id": "dornfelder", "name": "Dornfelder", "grape_type": "red", "origin_country": "germany",
     "description_pt": "Cruzamento alemão moderno, produz vinhos tintos de cor profunda e sabor frutado.",
     "description_en": "Modern German cross, produces deeply colored, fruity red wines.",
     "aromatic_notes": ["Cherry", "Blackberry", "Plum", "Herbs"],
     "flavor_notes": ["Dark fruits", "Soft tannins", "Earth"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio", "alcohol": "12-13%"},
     "aging_potential": "2-5 anos", "best_regions": ["Pfalz", "Rheinhessen"], "climate_preference": "Frio a moderado"},
    
    # ===== AUSTRIA - WHITE GRAPES =====
    {"grape_id": "gruner_veltliner", "name": "Grüner Veltliner", "grape_type": "white", "origin_country": "austria",
     "description_pt": "A uva emblemática da Áustria, produz vinhos frescos com notas de pimenta branca.",
     "description_en": "Austria's emblematic grape, produces fresh wines with white pepper notes.",
     "aromatic_notes": ["White pepper", "Citrus", "Green apple", "Herbs", "Mineral"],
     "flavor_notes": ["Lentil", "Pea shoot", "Grapefruit"],
     "structure": {"acidity": "Alta", "tannin": "N/A", "body": "Leve a médio", "alcohol": "11-14%"},
     "aging_potential": "2-15 anos", "best_regions": ["Wachau", "Kamptal", "Kremstal"], "climate_preference": "Frio a moderado"},
    
    # ===== NEW WORLD - RED GRAPES =====
    {"grape_id": "zinfandel", "name": "Zinfandel", "grape_type": "red", "origin_country": "usa",
     "description_pt": "A mesma Primitivo italiana, tornou-se emblemática da Califórnia. Vinhos frutados e potentes.",
     "description_en": "The same as Italian Primitivo, became emblematic of California. Fruity, powerful wines.",
     "aromatic_notes": ["Blackberry", "Raspberry", "Black pepper", "Jam", "Spice"],
     "flavor_notes": ["Dark fruits", "Vanilla", "Chocolate", "Licorice"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Encorpado", "alcohol": "14-17%"},
     "aging_potential": "3-10 anos", "best_regions": ["California (Sonoma, Lodi)", "Puglia (as Primitivo)"], "climate_preference": "Quente"},
    
    {"grape_id": "petite_sirah", "name": "Petite Sirah / Durif", "grape_type": "red", "origin_country": "usa",
     "description_pt": "Cruzamento francês que prosperou na Califórnia. Vinhos muito escuros e tânicos.",
     "description_en": "French cross that thrived in California. Very dark, tannic wines.",
     "aromatic_notes": ["Blackberry", "Plum", "Pepper", "Chocolate", "Coffee"],
     "flavor_notes": ["Dark fruits", "Tar", "Licorice", "Smoke"],
     "structure": {"acidity": "Média", "tannin": "Muito alto", "body": "Encorpado", "alcohol": "13-16%"},
     "aging_potential": "10-20 anos", "best_regions": ["California", "Australia"], "climate_preference": "Quente"},
    
    {"grape_id": "pinotage", "name": "Pinotage", "grape_type": "red", "origin_country": "south_africa",
     "description_pt": "Cruzamento sul-africano de Pinot Noir x Cinsault, produz vinhos únicos com notas defumadas.",
     "description_en": "South African cross of Pinot Noir x Cinsault, produces unique wines with smoky notes.",
     "aromatic_notes": ["Plum", "Smoke", "Banana", "Coffee", "Tar"],
     "flavor_notes": ["Dark fruits", "Chocolate", "Earth", "Rubber"],
     "structure": {"acidity": "Média", "tannin": "Médio-alto", "body": "Médio a encorpado", "alcohol": "13-15%"},
     "aging_potential": "5-15 anos", "best_regions": ["Stellenbosch", "Swartland"], "climate_preference": "Quente"},
    
    {"grape_id": "carmenere", "name": "Carménère", "grape_type": "red", "origin_country": "chile",
     "description_pt": "Uva de Bordeaux quase extinta, renasceu no Chile. Notas herbáceas e de pimentão.",
     "description_en": "Nearly extinct Bordeaux grape, reborn in Chile. Herbaceous and green pepper notes.",
     "aromatic_notes": ["Green pepper", "Red fruits", "Chocolate", "Coffee", "Herbs"],
     "flavor_notes": ["Plum", "Spice", "Smoke", "Leather"],
     "structure": {"acidity": "Média", "tannin": "Médio", "body": "Médio a encorpado", "alcohol": "13-14%"},
     "aging_potential": "5-12 anos", "best_regions": ["Colchagua", "Maipo", "Cachapoal"], "climate_preference": "Moderado a quente"},
    
    {"grape_id": "tannat", "name": "Tannat", "grape_type": "red", "origin_country": "uruguay",
     "description_pt": "Originária do Madiran francês, tornou-se emblemática do Uruguai. Extremamente tânica.",
     "description_en": "Originally from French Madiran, became emblematic of Uruguay. Extremely tannic.",
     "aromatic_notes": ["Blackberry", "Plum", "Violet", "Leather", "Earth"],
     "flavor_notes": ["Dark fruits", "Tar", "Chocolate", "Spice"],
     "structure": {"acidity": "Alta", "tannin": "Muito alto", "body": "Encorpado", "alcohol": "13-15%"},
     "aging_potential": "10-25 anos", "best_regions": ["Uruguay", "Madiran (France)"], "climate_preference": "Moderado a quente"},
    
    # ===== NEW WORLD - WHITE GRAPES =====
    {"grape_id": "torrontes", "name": "Torrontés", "grape_type": "white", "origin_country": "argentina",
     "description_pt": "A uva branca emblemática da Argentina, intensamente aromática como Muscat.",
     "description_en": "Argentina's emblematic white grape, intensely aromatic like Muscat.",
     "aromatic_notes": ["Rose", "Peach", "Citrus", "Geranium", "Musk"],
     "flavor_notes": ["Stone fruit", "Floral", "Spice"],
     "structure": {"acidity": "Média", "tannin": "N/A", "body": "Médio", "alcohol": "12-14%"},
     "aging_potential": "1-3 anos", "best_regions": ["Salta", "La Rioja", "Mendoza"], "climate_preference": "Quente e seco"},
]
